version: "3.8"

# Simplified version for local development
# Only essential components without redundancy

services:
  # OpenTelemetry Collector - central collection point
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-dev
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-dev.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC - your application connects here
      - "4318:4318" # OTLP HTTP
    networks:
      - observability

  # Jaeger - for viewing traces
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-dev
    ports:
      - "16686:16686" # Jaeger UI - http://localhost:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - observability

  # Prometheus - for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports:
      - "9090:9090" # Prometheus UI - http://localhost:9090
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    networks:
      - observability

  # Grafana - unified interface for everything
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dev
    ports:
      - "3000:3000" # Grafana UI - http://localhost:3000 (admin/admin)
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-dev.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus
      - jaeger
    networks:
      - observability

networks:
  observability:
    driver: bridge
# How to use:
# 1. docker-compose -f docker-compose.dev.yml up -d
# 2. In your application: OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
# 3. Open:
#    - Grafana: http://localhost:3000 (admin/admin)
#    - Jaeger: http://localhost:16686
#    - Prometheus: http://localhost:9090
