# Simplified OpenTelemetry Collector configuration for development

receivers:
  # OTLP receiver - your application sends data here
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Batch processor - groups data
  batch:
    timeout: 1s
    send_batch_size: 512

exporters:
  # Jaeger exporter - traces go to Jaeger
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Prometheus exporter - metrics for Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Logging exporter - for debugging (visible in docker logs)
  logging:
    loglevel: info

service:
  pipelines:
    # Traces: application -> collector -> Jaeger
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]

    # Metrics: application -> collector -> Prometheus
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]

    # Logs: application -> collector -> console (no Loki yet)
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
