# Simplified Prometheus configuration for development

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # OpenTelemetry Collector - metrics from your application
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    scrape_interval: 5s
    metrics_path: /metrics

  # Your application directly (if using Prometheus exporter)
  - job_name: "my-app"
    static_configs:
      - targets: ["host.docker.internal:8080"] # Your application on host
    metrics_path: /metrics
    scrape_interval: 5s
