# Упрощенная конфигурация Prometheus для разработки

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus сам себя
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # OpenTelemetry Collector - метрики от вашего приложения
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    scrape_interval: 5s
    metrics_path: /metrics

  # Ваше приложение напрямую (если использует Prometheus exporter)
  - job_name: "my-app"
    static_configs:
      - targets: ["host.docker.internal:8080"] # Ваше приложение на хосте
    metrics_path: /metrics
    scrape_interval: 5s
